export default {
    OPEN_MODAL: "OPEN_MODAL",
    CLOSE_MODAL: "CLOSE_MODAL",
    STOP_PAGINATION_FETCH: "STOP_PAGINATION_FETCH",
    START_PAGINATION_FETCH: "START_PAGINATION_FETCH",
    PAGINATION_FETCH: "PAGINATION_FETCH",
}
